name: Verify
on:
  push:

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: "./.github/actions/setup"

      - name: Build
        run: task build
